image: node:16

variables:
  AWS_DEFAULT_REGION: ${{ values.region }}

stages:
  - deploy
  - manual_start
  - manual_stop
  - manual_remove

deploy_to_aws:
  stage: deploy
  before_script:
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
    - npm install
    - npm install -g serverless
  script:
    - serverless deploy --stage ${{ values.stage }} --verbose

starting:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: manual_start
  when: manual
  script:
    - aws lambda invoke --function-name ${{ values.componentId }}-start test.log

stopping:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: manual_stop
  when: manual
  script:
    - aws lambda invoke --function-name ${{ values.componentId }}-stop test.log

removing:
  stage: manual_remove
  when: manual
  before_script:
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
    - npm install
    - npm install -g serverless
  script:
    - serverless remove --stage ${{ values.stage }} --verbose